spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plip_monitor_db
    username: plip
    password: plip123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true